### ISSUE TITLE
Good semantic tags

### ISSUE THREAD

**Issue by tresorsawasawa** [chiztechnology/Israel-Portfolio#2]
Hi @chiztechnology 

On an excellent semantics tag, please make sure you update this  line of code: 
```HTML
<h2 class="intro-text">I’m Mariane Glad to see you!</h2>
```
to:
```HTML
<h1 class="intro-text">I’m Mariane Glad to see you!</h1>
```
I noticed that I missed it from your requirements. 

Thanks

**Comment by chiztechnology** [comment]
it's done, thank you for that
